{alerting: {alertmanagers: [{static_configs: [{targets: null}]}]}, global: {evaluation_interval: 1s,
    scrape_interval: 200ms}, rule_files: [10000samples_quantile.yml], scrape_configs: [
    {job_name: fake_metric, static_configs: [{targets: ['localhost:8000', 'localhost:8001',
            'localhost:8002', 'localhost:8003', 'localhost:8004', 'localhost:8005',
            'localhost:8006', 'localhost:8007', 'localhost:8008', 'localhost:8009',
            'localhost:8010', 'localhost:8011', 'localhost:8012', 'localhost:8013',
            'localhost:8014', 'localhost:8015', 'localhost:8016', 'localhost:8017',
            'localhost:8018', 'localhost:8019', 'localhost:8020', 'localhost:8021',
            'localhost:8022', 'localhost:8023', 'localhost:8024', 'localhost:8025',
            'localhost:8026', 'localhost:8027', 'localhost:8028', 'localhost:8029',
            'localhost:8030', 'localhost:8031', 'localhost:8032', 'localhost:8033',
            'localhost:8034', 'localhost:8035', 'localhost:8036', 'localhost:8037',
            'localhost:8038', 'localhost:8039', 'localhost:8040', 'localhost:8041',
            'localhost:8042', 'localhost:8043', 'localhost:8044', 'localhost:8045',
            'localhost:8046', 'localhost:8047', 'localhost:8048', 'localhost:8049',
            'localhost:8050', 'localhost:8051', 'localhost:8052', 'localhost:8053',
            'localhost:8054', 'localhost:8055', 'localhost:8056', 'localhost:8057',
            'localhost:8058', 'localhost:8059', 'localhost:8060', 'localhost:8061',
            'localhost:8062', 'localhost:8063', 'localhost:8064', 'localhost:8065',
            'localhost:8066', 'localhost:8067', 'localhost:8068', 'localhost:8069',
            'localhost:8070', 'localhost:8071', 'localhost:8072', 'localhost:8073',
            'localhost:8074', 'localhost:8075', 'localhost:8076', 'localhost:8077',
            'localhost:8078', 'localhost:8079', 'localhost:8080', 'localhost:8081',
            'localhost:8082', 'localhost:8083', 'localhost:8084', 'localhost:8085',
            'localhost:8086', 'localhost:8087', 'localhost:8088', 'localhost:8089',
            'localhost:8090', 'localhost:8091', 'localhost:8092', 'localhost:8093',
            'localhost:8094', 'localhost:8095', 'localhost:8096', 'localhost:8097',
            'localhost:8098', 'localhost:8099', 'localhost:8100', 'localhost:8101',
            'localhost:8102', 'localhost:8103', 'localhost:8104', 'localhost:8105',
            'localhost:8106', 'localhost:8107', 'localhost:8108', 'localhost:8109',
            'localhost:8110', 'localhost:8111', 'localhost:8112', 'localhost:8113',
            'localhost:8114', 'localhost:8115', 'localhost:8116', 'localhost:8117',
            'localhost:8118', 'localhost:8119', 'localhost:8120', 'localhost:8121',
            'localhost:8122', 'localhost:8123', 'localhost:8124', 'localhost:8125',
            'localhost:8126', 'localhost:8127', 'localhost:8128', 'localhost:8129',
            'localhost:8130', 'localhost:8131', 'localhost:8132', 'localhost:8133',
            'localhost:8134', 'localhost:8135', 'localhost:8136', 'localhost:8137',
            'localhost:8138', 'localhost:8139', 'localhost:8140', 'localhost:8141',
            'localhost:8142', 'localhost:8143', 'localhost:8144', 'localhost:8145',
            'localhost:8146', 'localhost:8147', 'localhost:8148', 'localhost:8149',
            'localhost:8150', 'localhost:8151', 'localhost:8152', 'localhost:8153',
            'localhost:8154', 'localhost:8155', 'localhost:8156', 'localhost:8157',
            'localhost:8158', 'localhost:8159', 'localhost:8160', 'localhost:8161',
            'localhost:8162', 'localhost:8163', 'localhost:8164', 'localhost:8165',
            'localhost:8166', 'localhost:8167', 'localhost:8168', 'localhost:8169',
            'localhost:8170', 'localhost:8171', 'localhost:8172', 'localhost:8173',
            'localhost:8174', 'localhost:8175', 'localhost:8176', 'localhost:8177',
            'localhost:8178', 'localhost:8179', 'localhost:8180', 'localhost:8181',
            'localhost:8182', 'localhost:8183', 'localhost:8184', 'localhost:8185',
            'localhost:8186', 'localhost:8187', 'localhost:8188', 'localhost:8189',
            'localhost:8190', 'localhost:8191', 'localhost:8192', 'localhost:8193',
            'localhost:8194', 'localhost:8195', 'localhost:8196', 'localhost:8197',
            'localhost:8198', 'localhost:8199']}]}]}
