{rule_files: [10samples_avg.yml], scrape_configs: [{job_name: fake-exporter, scrape_interval: 100ms,
      static_configs: [{targets: ['localhost:10000', 'localhost:10001', 'localhost:10002',
            'localhost:10003', 'localhost:10004', 'localhost:10005', 'localhost:10006',
            'localhost:10007', 'localhost:10008', 'localhost:10009']}]}]}
