{alerting: {alertmanagers: [{static_configs: [{targets: null}]}]}, global: {evaluation_interval: 1s,
    scrape_interval: 200ms}, rule_files: [10000samples_sum.yml], scrape_configs: [
    {job_name: fake_metric, static_configs: [{targets: ['localhost:8000', 'localhost:8001',
            'localhost:8002', 'localhost:8003', 'localhost:8004', 'localhost:8005',
            'localhost:8006', 'localhost:8007', 'localhost:8008', 'localhost:8009',
            'localhost:8010', 'localhost:8011', 'localhost:8012', 'localhost:8013',
            'localhost:8014', 'localhost:8015', 'localhost:8016', 'localhost:8017',
            'localhost:8018', 'localhost:8019']}]}]}
