{alerting: {alertmanagers: [{static_configs: [{targets: null}]}]}, global: {evaluation_interval: 1s,
    scrape_interval: 100ms}, rule_files: [1000samples_sum.yml], scrape_configs: [
    {job_name: fake_metric, static_configs: [{targets: ['localhost:8000']}]}]}
